# Write and read product folder

In [1]:
import numpy as np

from arepytools.io import (
    create_new_metadata,
    create_product_folder,
    read_metadata,
    read_raster_with_raster_info,
    write_metadata,
    write_raster_with_raster_info,
)
from arepytools.io.metadata import ECellType, RasterInfo, SwathInfo
from arepytools.timing.precisedatetime import PreciseDateTime as Pdt

In [2]:
# create a ProductFolder
output_product = "test_out"
pf = create_product_folder(output_product)
# get channel 1 raster filename and metadata filename
ch1_raster_filename = pf.get_channel_data(1)
ch1_metadata_filename = pf.get_channel_metadata(1)
# creating a raster info for channel 1
raster_info = RasterInfo(lines=5, samples=5, celltype=ECellType.float32, filename=ch1_raster_filename.name)
# creating a metadata object
ch1_metadata = create_new_metadata()
# adding raster info to it
ch1_metadata.insert_element(raster_info)

In [3]:
# write the metadata file with only RasterInfo element
write_metadata(metadata_file=ch1_metadata_filename, metadata_obj=ch1_metadata)

In [4]:
# create an additional metadata element, for instance the SwathInfo
swath_info = SwathInfo(swath_i="SwathName", polarization_i="H/V", acquisition_prf_i=2000)
swath_info.acquisition_start_time = Pdt.from_utc_string("1 JAN 2021 00:00:00.00000")

In [5]:
# insert the metadata element in the first metadata channel of the first product folder channel
ch1_metadata.insert_element(swath_info)

# write the metadata file, overwriting the previous one
write_metadata(metadata_file=ch1_metadata_filename, metadata_obj=ch1_metadata)

In [6]:
# write the raster file
data = np.arange(4).reshape((2, 2))
write_raster_with_raster_info(raster_file=ch1_raster_filename, data=data, raster_info=raster_info, start_point=(1, 1))

In [7]:
# read metadata and print the raster info
meta = read_metadata(metadata_file=ch1_metadata_filename)
print(meta.get_raster_info())


MetaDataElement: RasterInfo

            file_name: test_out_0001
                lines: 5
              samples: 5
  header_offset_bytes: 0
     row_prefix_bytes: 0
           byte_order: EByteOrder.le
            cell_type: ECellType.float32
          lines_start: 0.0
     lines_start_unit: 
           lines_step: 0.0
      lines_step_unit: 
        samples_start: 0.0
   samples_start_unit: 
         samples_step: 0.0
    samples_step_unit: 
        invalid_value: None
          format_type: None



In [8]:
# read and print the SwathInfo
print(meta.get_swath_info())


MetaDataElement: SwathInfo

                                swath: SwathName
                         polarization: EPolarization.hv
                      acquisition_prf: 2000.0
                 acquisition_prf_unit: Hz
              swath_acquisition_order: 0
                                 rank: 0
                     range_delay_bias: 0.0
                range_delay_bias_unit: s
               acquisition_start_time: 01-JAN-2021 00:00:00.000000000000
          acquisition_start_time_unit: Utc
 azimuth_steering_rate_reference_time: 0.0
       az_steering_rate_ref_time_unit: s
                     echoes_per_burst: 0
            azimuth_steering_rate_pol: (0.0, 0.0, 0.0)
                              rx_gain: None
                        channel_delay: None



In [9]:
# Read and display raster
data_in = read_raster_with_raster_info(raster_file=ch1_raster_filename, raster_info=raster_info)
print(data_in)

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 2. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
# delete the product
pf.delete()